Work-section
sj1978/Portfolio-project-1 pull request #2
Opened 2021-09-16 22:54 UTC by sj1978

in this section I:
.Created a section with an H2.
.Created an image.
.Created a work section
Created a button.

2021-09-16 23:11 UTC, mke2111 requested changes
### Hey @sj1978, 

**This is a great project you have going on, well-done lad**. 
   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️
_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 23:13 UTC, mke2111 commented on index.html
> +            <h3>Multi-Post Stories</h3>
- [ ] My Recent Work is the section title. You have repeated it for every project. You should only have one for the entire section

2021-09-16 23:18 UTC, mke2111 commented on index.html
> +            <h3>Multi-Post Stories</h3>
- [ ] All the images for the projects are not visible. Give this a fix.

2021-09-16 23:24 UTC, mke2111 commented on index.html
> +    </section>
- [ ] For each project, ensure the section uses the font and colors background and font) defined for the template. Also put the margins (top, bottom, left, right) defined in the design into consideration.
Your Project
![Screenshot from 2021-09-17 02-21-13](https://user-images.githubusercontent.com/65501535/133698690-95e3de8c-e4a9-4b53-ab2e-285e494ef7ab.png)

Original design
![Screenshot from 2021-09-17 02-23-58](https://user-images.githubusercontent.com/65501535/133699133-434e4ef8-3969-4167-a708-55cc9d98f12c.png)

2021-09-16 23:29 UTC, mke2111 commented on index.html
>      </section>
- [ ] For this entire section, make it match the given design.
Your page
![Screenshot from 2021-09-17 02-27-25](https://user-images.githubusercontent.com/65501535/133701310-0f1ac20a-6e0a-433e-b892-6dff51292893.png)

Original page

![Screenshot from 2021-09-17 02-29-16](https://user-images.githubusercontent.com/65501535/133701361-039c4dba-ba0e-41df-bb4c-14c29cb4bd8d.png)

2021-09-17 18:17 UTC, rukundoeric approved these changes
Hi @sj1978,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-17 19:40 UTC, merged